
services:
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=state-manager-docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: